#Requires -RunAsAdministrator
<#
.SYNOPSIS
    ClassroomOS Agent Installer
    Installs the ClassroomOS agent as a Windows service on a client machine.

.DESCRIPTION
    Run this script once on each client PC (as Administrator).
    It will:
      1. Copy agent files to C:\ClassroomAgent\
      2. Install Python dependencies (for dev mode) OR copy pre-built agent.exe
      3. Register the Windows service (auto-start, restart on failure)
      4. Open firewall port 9000
      5. Write config.json with the provided shared secret

.PARAMETER ConsoleIP
    IP address of the admin console machine

.PARAMETER SharedSecret
    Shared secret (SHA-256 hex, generated by the console on first run)
    Copy this from the console's config.json after setting your password.

.PARAMETER AgentSourcePath
    Path to the agent source folder (defaults to script's parent directory)

.PARAMETER UseExe
    If set, copies agent.exe instead of raw Python files
    Set this after building with build_agent.ps1

.EXAMPLE
    .\install_agent.ps1 -ConsoleIP "192.168.1.10" -SharedSecret "abc123..."
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$ConsoleIP,

    [Parameter(Mandatory=$true)]
    [string]$SharedSecret,

    [string]$AgentSourcePath = "$PSScriptRoot\..\agent",

    [switch]$UseExe = $false,

    [int]$ListenPort = 9000
)

$ErrorActionPreference = "Stop"
$InstallDir = "C:\ClassroomAgent"
$ServiceName = "ClassroomOSAgent"
$ServiceDisplay = "ClassroomOS Agent"

Write-Host ""
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "  ClassroomOS Agent Installer v1.0"    -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Create install directory ────────────────────────────────────────
Write-Host "[1/7] Creating install directory..." -ForegroundColor Yellow
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}

# ── Step 2: Copy agent files ─────────────────────────────────────────────────
Write-Host "[2/7] Copying agent files..." -ForegroundColor Yellow

if ($UseExe) {
    # Copy just the compiled executable produced by build_agent.ps1
    $Candidates = @(
        (Join-Path $PSScriptRoot "dist\ClassroomOSAgent.exe"),
        (Join-Path $PSScriptRoot "dist\ClassroomOSAgent\ClassroomOSAgent.exe"),
        (Join-Path $AgentSourcePath "dist\ClassroomOSAgent.exe")
    )
    $ExePath = $Candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
    if (-not $ExePath) {
        Write-Error "ClassroomOSAgent.exe not found. Run build_agent.ps1 first. Looked in:`n  $($Candidates -join "`n  ")"
    }
    Copy-Item $ExePath "$InstallDir\ClassroomOSAgent.exe" -Force
} else {
    # Copy full Python source (for development/testing)
    Copy-Item "$AgentSourcePath\*" $InstallDir -Recurse -Force

    # The agent puts both its own folder and ..\shared on sys.path. Once
    # installed to C:\ClassroomAgent there is no sibling shared\ folder, so
    # protocol.py is placed directly alongside the agent as well — that is the
    # copy `from protocol import ...` actually resolves against.
    $SharedDir = Join-Path $AgentSourcePath "..\shared"
    if (Test-Path $SharedDir) {
        $SharedTarget = Join-Path $InstallDir "shared"
        if (-not (Test-Path $SharedTarget)) {
            New-Item -ItemType Directory -Path $SharedTarget -Force | Out-Null
        }
        Copy-Item "$SharedDir\*" $SharedTarget -Recurse -Force
        Copy-Item "$SharedDir\*.py" $InstallDir -Force
    } else {
        Write-Error "shared\ folder not found at $SharedDir — cannot install the protocol module."
    }
}

Write-Host "    Files copied to $InstallDir" -ForegroundColor Green

# ── Step 3: Write config.json ────────────────────────────────────────────────
Write-Host "[3/7] Writing agent config..." -ForegroundColor Yellow

$Config = @{
    shared_secret               = $SharedSecret
    console_ip                  = $ConsoleIP
    listen_port                 = $ListenPort
    ui_port                     = 9001
    lock_hotkey_disabled        = $true
    blocklist                   = @()
    usb_enabled                 = $true
    internet_enabled            = $true
    autologoff_idle_minutes     = 0
    autologoff_warning_seconds  = 30
    handin_folder               = "C:\HandIn"
    backup_dir                  = ""
} | ConvertTo-Json -Depth 3

$ConfigPath = "$InstallDir\config.json"
$Config | Out-File -FilePath $ConfigPath -Encoding utf8 -Force

# Lock the config down. It holds the shared secret that authenticates every
# console command, and $InstallDir sits under C:\ where students can read by
# default — without this a student could read the secret and drive their own
# agent. The rest of $InstallDir stays readable because the in-session UI
# helper runs as the student and has to load the code from there.
icacls $ConfigPath /inheritance:r /grant "SYSTEM:(F)" "Administrators:(F)" *> $null
Write-Host "    config.json written (readable only by SYSTEM + Administrators)" -ForegroundColor Green

# ── Step 4: Install Python dependencies (source mode only) ───────────────────
if (-not $UseExe) {
    Write-Host "[4/7] Installing Python dependencies..." -ForegroundColor Yellow
    $AgentReqs = @("psutil", "pywin32", "pyautogui", "mss", "Pillow")
    foreach ($pkg in $AgentReqs) {
        Write-Host "    Installing $pkg..." -ForegroundColor Gray
        python -m pip install $pkg --quiet *> $null
    }

    # pywin32 needs a post-install step to register its DLLs before it can host
    # a service. Its location depends on the Python version and install scheme,
    # so ask the interpreter instead of guessing a hard-coded 3.11 path.
    $PostInstall = python -c "import sysconfig, os; p = os.path.join(sysconfig.get_path('scripts'), 'pywin32_postinstall.py'); print(p if os.path.isfile(p) else '')"
    if ($PostInstall) {
        Write-Host "    Running pywin32 post-install..." -ForegroundColor Gray
        python $PostInstall -install *> $null
    } else {
        Write-Warning "    pywin32_postinstall.py not found — the service may fail to start."
        Write-Warning "    Fix with: python -m pywin32_postinstall -install"
    }
    Write-Host "    Dependencies installed" -ForegroundColor Green
} else {
    Write-Host "[4/7] Skipping Python dependencies (using .exe)" -ForegroundColor Gray
}

# ── Step 5: Register Windows Service ─────────────────────────────────────────
Write-Host "[5/7] Registering Windows service..." -ForegroundColor Yellow

# Remove existing service if present
$existing = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existing) {
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    sc.exe delete $ServiceName | Out-Null
    Start-Sleep -Seconds 2
}

if ($UseExe) {
    # Register .exe directly as service
    sc.exe create $ServiceName `
        binPath= "$InstallDir\ClassroomOSAgent.exe" `
        DisplayName= $ServiceDisplay `
        start= auto `
        obj= LocalSystem | Out-Null
} else {
    # Register via Python
    Set-Location $InstallDir
    python agent_service.py install | Out-Null
}

# Set service description
sc.exe description $ServiceName "ClassroomOS client management agent. Do not stop this service." | Out-Null

# Configure failure recovery (restart on crash, 3 times, then 1-minute delay)
sc.exe failure $ServiceName reset= 86400 actions= restart/5000/restart/10000/restart/60000 | Out-Null

Write-Host "    Service '$ServiceName' registered" -ForegroundColor Green

# ── Step 6: Open firewall port ───────────────────────────────────────────────
Write-Host "[6/7] Configuring firewall..." -ForegroundColor Yellow

# Remove old rule if exists
netsh advfirewall firewall delete rule name="ClassroomOS Agent" 2>&1 | Out-Null

# Add inbound rule for agent port
netsh advfirewall firewall add rule `
    name="ClassroomOS Agent" `
    dir=in `
    action=allow `
    protocol=TCP `
    localport=$ListenPort `
    profile=any `
    enable=yes | Out-Null

Write-Host "    Firewall rule added (TCP port $ListenPort inbound)" -ForegroundColor Green

# ── Step 7: Start service ─────────────────────────────────────────────────────
Write-Host "[7/7] Starting ClassroomOS Agent service..." -ForegroundColor Yellow
Start-Service -Name $ServiceName
Start-Sleep -Seconds 2

$svc = Get-Service -Name $ServiceName
if ($svc.Status -eq "Running") {
    Write-Host "    Service is RUNNING ✓" -ForegroundColor Green
} else {
    Write-Warning "    Service status: $($svc.Status) — check agent.log for errors"
}

# ── Done ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "  Installation complete!" -ForegroundColor Green
Write-Host "  Agent installed at: $InstallDir" -ForegroundColor Gray
Write-Host "  Log file:           $InstallDir\agent.log" -ForegroundColor Gray
Write-Host "  Console IP:         $ConsoleIP" -ForegroundColor Gray
Write-Host "  Listening on port:  $ListenPort" -ForegroundColor Gray
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host ""
